### ISSUE TITLE
GA property setup

### ISSUE THREAD

**Issue by quochuy** [phase2/tvjs-google-analytics#3]
Hi,

How should I setup my GA property?
If I set is as a website, the stats only show Pageviews instead of Screenviews.
If I set is as a mobile app, it requires me to use Firebase...

Thanks
Huy

**Comment by febbraro** [comment]
I have my properties setup as mobile, but I see now that they require a connection to Firebase. The SDK uses the measurement protocol, so I would see if you can connect it to Firebase and see where the measurement protocol sends your data.

**Comment by febbraro** [comment]
See the section at the bottom of "Setup using the older Google Analytics Services SDK" 

https://support.google.com/analytics/answer/2587086?hl=en

This may be how we have to do it now.

**Comment by quochuy** [comment]
It works!
Thank you.
